services:
  web:
    build: ./backend
    container_name: ondas_backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    restart: always

#   nginx:
#     image: nginx:latest
#     container_name: ondas_nginx
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./ondas_crm.html:/usr/share/nginx/html/index.html
#       - ./certbot/conf:/etc/letsencrypt
#       - ./certbot/www:/var/www/certbot
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - web
#     restart: always
